config/routes.rb
Rails.application.routes.draw do


  root'pages#home'
  devise_for :users,
             controllers: { registrations: 'registrations'}

  resources :users, only: [:show]
  resources :services,except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'expertise_area'
      get 'location'
      get 'preload'
      get 'preview'
    end

    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :traveler_reviews, only: [:create, :detroy]
  resources :guide_reviews, only: [:create, :detroy]

  get '/your_bookings' => 'reservations#your_bookings'
  get '/your_reservations' => 'reservations#your_reservations'
  get 'search' => 'pages#search'

end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations

  has_many :traveler_reviews


geocoded_by :city
after_validation :geocode, if: :city_changed?


  validates :gender, presence:true
  validates :language, presence:true


  def cover_photo(size)
    if self.photos.length > 0
      self.photos[0].image.url(size)
    else
      "blank.jpg"
    end
  end

  def average_rating
    traveler_reviews.count == 0 ? 0 : traveler_reviews.average(:star).round(2).to_i


  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorised, only: [:listing, :pricing, :description, :photo_upload, :expertise_area, :location, :update]

  def index
    @service = current_user.services
    @services = @service.all
  end

  def new
    @service = current_user.services.build
  end

  def create
    @service = current_user.services.build(service_params)
    if @service.save
      redirect_to listing_service_path(@service), notice: "Saved..."
    else
      flash[:alert] = "Something went wrong..."
      render :new
    end
  end

  def show
    @photos= @service.photos
    @traveler_reviews = @service.traveler_reviews
  end

  def listing
    set_service
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @service.photos

  end

  def expertise_area
  end

  def location
  end

  def update

    new_params= service_params
    new_params = service_params.merge(active: true) if is_ready_service

    if @service.update(new_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  # -------RESERVATIONS ------------

  def preload
    today = Date.today
    reservations = @service.reservations.where("start_date >= ? OR end_date >= ?", today, today)

    render json: reservations
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @service)
    }

    render json: output
  end




  private

    def is_conflict(start_date, end_date, service)
      check = service.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
      check.size > 0? true : false
    end

    def set_service
      @service = Service.find(params[:id])
    end

    def service_params
      params.require(:service).permit(:gender,:city, :language, :price, :guide_name, :summary, :has_outdoors,:has_shopping,:has_museum,:has_monuments, :has_food,:has_night, :time_spent,:active)
    end

    def  is_authorised
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @service.user_id
    end

    def is_ready_service
      !@service.active && !@service.price.blank? && !@service.guide_name.blank? && !@service.photos.blank? && !@service.city.blank?
    end


end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_service_menu.html.erb
<ul class="sidebar-list">

  <li class="sidebar-item">
    <%= link_to "Listing", listing_service_path, class:"sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>

  <li class="sidebar-item">
    <%= link_to "Description", description_service_path, class:"sidebar-link active" %>
    <% if !@service.guide_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>



  <li class="sidebar-item">
    <%= link_to "Photos", photo_upload_service_path, class:"sidebar-link active" %>
    <% if !@service.photos.blank? %>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>

  <li class="sidebar-item">
    <%= link_to "Expertise Area", expertise_area_service_path, class:"sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>

  <li class="sidebar-item">
    <%= link_to "Location", location_service_path, class:"sidebar-link active" %>
    <% if !@service.city.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>

  <li class="sidebar-item">
    <%= link_to "Pricing", pricing_service_path, class:"sidebar-link active" %>
    <% if !@service.price.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>

</ul>
<hr/>

<% is_ready = !@service.active && !@service.price.blank? && !@service.guide_name.blank? && !@service.photos.blank? && !@service.city.blank? %>

<%= form_for @service do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>

app/views/services/_services_list.html.erb
<% services.each do |service| %>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <%= image_tag service.cover_photo (:medium) %>
      </div>
      <div class="panel-body">
        <%= link_to service.guide_name, service %><br/>
        $<%= service.price %> per day - <%= service.language %>
        <div id="star_<%= service.id %>"></div> <%= pluralize(service.average_rating, "review") %>
      </div>
    </div>
  </div>

  <script>
    $('#star_<%= service.id %>').raty({
      path: '/assets',
      readOnly: true,
      score: <%= service.average_rating %>
    });
</script>
<% end %>

app/views/services/create.html.erb
<h1>Services#create</h1>
<p>Find me in app/views/services/create.html.erb</p>

app/views/services/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'service_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Description
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @service do |f| %>

            <div class="row">
              <div class="form-group">
                <label>Guide Name</label>
                <%= f.text_field :guide_name, placeholder: "What is your name?", class: "form-control", required: true %>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <label>Tell us about yourself!</label>
                <%= f.text_area :summary, rows: 5, placeholder: "Summary of what makes you unique", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/services/expertise_area.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'service_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Expertise Area
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @service do |f| %>

              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :has_shopping %> Shopping
                </div>
                <div class="col-md-4">
                  <%= f.check_box :has_food %> Food Spots
                </div>
                <div class="col-md-4">
                  <%= f.check_box :has_night %> Nightlife
                </div>
                <div class="col-md-4">
                  <%= f.check_box :has_museum %> Museums
                </div>
                <div class="col-md-4">
                  <%= f.check_box :has_outdoors %> Outdoor Activities
                </div>
                <div class="col-md-4">
                  <%= f.check_box :has_monuments %> Historical Monuments
                </div>
              </div>


              <br/><br/>

              <div class="text-center">
                <%= f.submit "Save", class: "btn btn-form" %>
              </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/services/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", services_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your bookings", your_bookings_path, class: "sidebar-link active" %></li>

    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Current Listing
      </div>
      <div class="panel-body">

        <% @services.each do |service| %>
          <div class="row">
            <div class="col-md-2">
              <%= image_tag service.cover_photo(:thumb) %>
            </div>
            <div class="col-md-7">
              <h4><%= service.guide_name %></h4>
            </div>
            <div class="col-md-3 right">
              <%= link_to "Update", listing_service_path(service), class: "btn btn-form" %>
            </div>
          </div>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/services/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'service_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Listing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @service do |f| %>

            <div class="row">

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Gender</label>
                  <%= f.select :gender, [["Female", "Female"], ["Male", "Male"]],
                                id: "gender", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Language</label>
                  <%= f.select :language, [["English", "English"],["French", "French"], ["Spanish", "Spanish"], ["German", "German"],["Swahili", "Swahili"], ["Arabic", "Arabic"],["Farsi", "Farsi"]],
                                id: "language", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Full-time or Part-time?</label>
                  <%= f.select :time_spent, [["Full-Time", "Full-Time"], ["Part-Time", "Part-Time"]],
                                id: "time_spent", prompt: "Select...", class: "form-control" %>
                </div>
              </div>




            </div>

            <div><%= f.submit "Save", class: "btn btn-normal" %></div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/services/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'service_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Location
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @service do |f| %>

            <div class="row">
              <div class="form-group">
                <label>City</label>
                <%= f.text_field :city, placeholder: "e.g Washington, DC", class: "form-control", required: true, id: "autoaddress" %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

<script>
  $(function() {
    $("#autoaddress").geocomplete();
  })
</script>

app/views/services/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create Your Guide Listing!
  </div>
  <div class="panel-body">
    <div class="container">

      <%= form_for @service do |f| %>

        <div class="row">

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Gender</label>
              <%= f.select :gender, [["Female", "Female"], ["Male", "Male"]],
                            id: "gender", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Language</label>
              <%= f.select :language, [["English", "English"],["French", "French"], ["Spanish", "Spanish"], ["German", "German"],["Swahili", "Swahili"], ["Arabic", "Arabic"],["Farsi", "Farsi"]],
                            id: "language", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Full-time or Part-time?</label>
              <%= f.select :time_spent, [["Full-Time", "Full-Time"], ["Part-Time", "Part-Time"]],
                            id: "time_spent", prompt: "Select...", class: "form-control" %>
            </div>
          </div>



        </div>

        <div><%= f.submit "Create My service", class: "btn btn-normal" %></div>

      <% end %>

    </div>
  </div>
</div>

app/views/services/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'service_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Photos
      </div>

      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!-- PHOTOS UPLOAD GOES HERE -->

              <%= form_for @service, url: service_photos_path(@service), method: 'post', html: {multipart: true} do |f| %>
                <div class="row">
                  <div class="form-group">
                    <span class="btn btn-default btn-file text-babu">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i> Select Photos
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    </span>
                  </div>
                </div>

                <div class="text-center">
                  <%= f.submit "Add Photos", class: "btn btn-form" %>
                </div>

              <% end %>
            </div>
          </div>

          <div id="photos"><%= render 'photos/photos_list' %></div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/services/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'service_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Pricing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @service do |f| %>

            <div class="row">
              <div class="form-group">
                <label>Booking Price (per day)</label>
                <%= f.text_field :price, placeholder: "enter your rate (per day)", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/services/show.html.erb
<!-- Image -->
<div class="row">
  <div class="col-md-12">
      <div class="row carousel-container">

        <div class="carousel-style">

          <% if @photos.length > 0 %>
              <div id="myCarousel" class="carousel slide" data-ride="carousel">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                <% @photos.each do |photo| %>
                    <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
                <% end %>
              </ol>

              <!-- Wrapper for slides -->
              <div class="carousel-inner">
                <% @photos.each do |photo| %>
                    <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                      <%= image_tag photo.image.url() %>
                    </div>
                <% end %>
              </div>

              <!-- Left and right controls -->
              <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          <% end %>
        </div>
      </div>
      <hr/>

    </div>
</div>
<br/>

<div class="row">
  <!-- LEFT PANEL -->
  <div class="col-md-8">

        <!-- Listing Name -->
        <div class="row text-center">
          <div class="col-md-8">
            <h2>Hello, my name is <%= @service.guide_name %></h2>
            <h4> I'm from <%= @service.city %> </h4>
          </div>
          <div class="col-md-4 text-center">
            <%= image_tag avatar_url(@service.user), class: "img-circle avatar-large" %><br/><br/>
            <%= @service.user.fullname %>
          </div>
        </div>
        <hr/>

        <!-- service Info -->
        <div class="row text-babu">
          <div class="row text-center row-space-1">
            <div class="col-md-4">
              <i class="fa fa-intersex fa-2x"></i>
            </div>
            <div class="col-md-4">
              <i class="fa fa-flag-o fa-2x"></i>
            </div>
            <div class="col-md-4">
              <i class="fa fa-clock-o fa-2x"></i>
            </div>
          </div>

          <div class="row text-center">
            <div class="col-md-4"><%= @service.gender %></div>
            <div class="col-md-4"><%= @service.language %></div>
            <div class="col-md-4"><%= @service.time_spent %></div>
          </div>

        </div>

          <hr/>






        <!-- About -->
  <div class="row div-service">
    <div class="col-md-12">
      <h3>Get to know me:</h3>
      <p><%= @service.summary %></p>
    </div>
  </div>
  <br/>
  <hr/>


        <!-- Amenities -->
        <div class="row div-service">
          <div class="col-md-3">
            <h3>Expertise Area</h3>
          </div>

          <div class="col-md-9">
            <div class="row">
              <div class="col-md-6">
                <ul class="expertise_area">
                  <li class="<%= 'text-line-through' if !@service.has_shopping %>">Shopping</li>
                  <li class="<%= 'text-line-through' if !@service.has_museum %>">Museums</li>
                  <li class="<%= 'text-line-through' if !@service.has_outdoors %>">Outdoor Activities</li>
              </div>
              <div class="col-md-6">
                <ul class="expertise_area">
                  <li class="<%= 'text-line-through' if !@service.has_monuments %>">Historical Monuments</li>
                  <li class="<%= 'text-line-through' if !@service.has_food %>">Fine Dining</li>
                  <li class="<%= 'text-line-through' if !@service.has_night %>">Night Life</li>
              </div>

            </div>
          </div>

          </div>


        <hr/>

    <!-- Review -->
    <div class="row div-service">
      <div class="col-md-12">
        <h3>
          <%= pluralize(@traveler_reviews.count, "Review") %>
          <span id="average_rating"></span>
        </h3>
        <div class="container">
          <div><%= render "reviews/traveler_list" %></div>
        </div>
      </div>
    </div>
    <br/>
    <hr/>


    <!-- GOOGLE MAP -->
    <div class="row div-service">

      <div id="map" style="width: 100%; height: 400px"></div>

      <script src="https://maps.googleapis.com/maps/api/js?key=#{ENV['maps_api_key]}&callback=initMap">
  </script>

      <script>
          function initialize() {
            var location = {lat: <%= @service.latitude %>, lng: <%= @service.longitude %>};
            var map = new google.maps.Map(document.getElementById('map'), {
              center: location,
              zoom: 14
            });

            var marker = new google.maps.Marker({
              position: location,
              map: map
            });

            var infoWindow = new google.maps.InfoWindow({
              content: '<div id="content"><%= image_tag @service.cover_photo(:medium) %></div>'
            });

            infoWindow.open(map, marker);
          }

          google.maps.event.addDomListener(window, 'load', initialize);
      </script>

    </div>
    <hr/>

    <!-- NEAR BY ROOMS -->
    <div class="row div-service">
      <h3>Near by Guides</h3>
      <% for service in @service.nearbys(10) %>
          <div class="col-md-4">
            <div class="panel panel-default">
              <div class="panel-heading preview">
                <%= image_tag service.cover_photo(:medium) %>
              </div>
              <div class="panel-body">
                <%= link_to service.guide_name, service %><br/>
                (<%= service.distance.round(2) %> Miles away)
              </div>
            </div>
          </div>
      <% end %>
    </div>

  </div>

    <!-- RIGHT PANEL -->
<div class="col-md-4">
  <!-- Reservation Form -->
  <%= render 'reservations/form' %>
</div>


  </div>




  <script>
    $('#average_rating').raty({
      path: '/assets',
      readOnly: true,
      score: <%= @service.average_rating %>
    });
  </script>

app/views/services/update.html.erb
<h1>Services#update</h1>
<p>Find me in app/views/services/update.html.erb</p>