config/routes.rb
Rails.application.routes.draw do


  root'pages#home'
  devise_for :users,
             controllers: { registrations: 'registrations'}

  resources :users, only: [:show]
  resources :services,except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'expertise_area'
      get 'location'
      get 'preload'
      get 'preview'
    end

    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :traveler_reviews, only: [:create, :detroy]
  resources :guide_reviews, only: [:create, :detroy]

  get '/your_bookings' => 'reservations#your_bookings'
  get '/your_reservations' => 'reservations#your_reservations'
  get 'search' => 'pages#search'

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :service
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :authenticate_user!

  def create
    service = Service.find(params[:service_id])

    if current_user == service.user
      flash[:alert] = "You cannot book yourself as a tour guide"
    else
      start_date = Date.parse(reservation_params[:start_date])
      end_date = Date.parse(reservation_params[:end_date])
      days = (end_date - start_date).to_i + 1

      @reservation = current_user.reservations.build(reservation_params)
      @reservation.service = service
      @reservation.price = service.price
      @reservation.total = service.price * days
      @reservation.save

      flash[:notice] = "Your Booking Request Has Been Submitted. You will receive a response within 24 hrs."

    end


    redirect_to service


  end

  def your_bookings
    @bookings = current_user.reservations.order(start_date: :asc)
  end

  def your_reservations
    @services = current_user.services
  end




  private
    def reservation_params
      params.require(:reservation).permit(:start_date, :end_date)
    end

end

app/views/reservations/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">

    <span> <i class="fa fa-bolt" style="color: #ffb400"></i> $<%= @service.price %></span>
    <span class="pull-right"> Per Day</span>

  </div>
  <div class="panel-body">

    <%=form_for([@service, @service.reservations.new]) do |f| %>
    <div class="row">
      <div class="col-md-6">
        <label> Start Date</label>
        <%= f.text_field :start_date, readonly: true, placeholder:"Enter your start date", class: "form-control datepicker" %>
      </div>

      <div class="col-md-6">
        <label> End Date</label>
          <%= f.text_field :end_date, readonly: true, placeholder:"Enter your end date", class: "form-control datepicker", disabled: true %>

      </div>
      </br>
      <p class="text-center"> A day is defined as a minimum of 4 hrs with a guide </p>

    </div>

    <h4 class="message-alert text-center"><span id="message"></span></h4>

    <div id="preview" style="display:none">
      <table class="reservation-table">
        <tbody>
          <tr>
            <td>Price</td>
            <td class="text-right">$<%= @service.price %></td>
          </tr>
          <tr>
            <td>Day(s)</td>
            <td class="text-right">x <span id="reservation_days"></span></td>
          </tr>
          <tr>
            <td class="total">Total</td>
            <td class="text-right">$<span id="reservation_total"></span></td>
          </tr>
        </tbody>
      </table>
    </div>



      <br/>

      <%= f.submit "Book Now", id: "btn_book", class: "btn btn-normal btn-block", disabled: true %>

    <% end %>

  </div>
</div>



<script>

  function checkDate(date) {
    dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
    return [$.inArray(dmy, unavailableDates) == -1];
  }

  $(function() {

    unavailableDates = [];

    $.ajax({
      url: '<%= preload_service_path(@service) %>',
      dateTyp: 'json',
      success: function(data) {

        $.each(data, function(arrID, arrValue) {
            for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
              unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
            }
        });

        $('#reservation_start_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: checkDate,
          onSelect: function(selected) {
            $('#reservation_end_date').datepicker("option", "minDate", selected);
            $('#reservation_end_date').attr("disabled", false);

            var start_date = $('#reservation_start_date').datepicker('getDate');
            var end_date = $('#reservation_end_date').datepicker('getDate');
            var days = (end_date - start_date)/1000/60/60/24 + 1;

            var input = {
              'start_date': start_date,
              'end_date': end_date
            }

            $.ajax({
              url: '<%= preview_service_path(@service) %>',
              data: input,
              success: function(data) {

                if(data.conflict) {
                  $('#message').text("The selected dates are unavailable");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = days * <%= @service.price %>
                  $('#reservation_days').text(days);
                  $('#reservation_total').text(total);


              }
            }

            });
          }
        });
        $('#reservation_end_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: checkDate,
          onSelect: function(selected) {
            $('#reservation_start_date').datepicker("option", "maxDate", selected);

            var start_date = $('#reservation_start_date').datepicker('getDate');
            var end_date = $('#reservation_end_date').datepicker('getDate');
            var days = (end_date - start_date)/1000/60/60/24 + 1;

            var input = {
              'start_date': start_date,
              'end_date': end_date
            }

            $.ajax({
              url: '<%= preview_service_path(@service) %>',
              data: input,
              success: function(data) {

                if(data.conflict) {
                  $('#message').text("The selected dates are unavailable");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = days * <%= @service.price %>
                  $('#reservation_days').text(days);
                  $('#reservation_total').text(total);


              }
            }

            });


          }
        });
      }

    });




  });
</script>

app/views/reservations/your_bookings.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", services_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your bookings", your_bookings_path, class: "sidebar-link active" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Your bookings
      </div>
      <div class="panel-body">

        <% @bookings.each do |booking| %>
          <div class="row">
            <div class="col-md-2">
              <%= booking.start_date.strftime('%v') %>
            </div>
            <div class="col-md-2">
              <%= link_to service_path(booking.service) do %>
                <%= image_tag booking.service.cover_photo(:thumb) %>
              <% end %>
            </div>
            <div class="col-md-5">
              <%= link_to booking.service.guide_name, service_path(booking.service) %><br/><br/>
              <span class="pull-right text-center">
                <%= image_tag avatar_url(booking.service.user), class: "img-circle avatar-small" %>
                <%= link_to user_path(booking.service.user) do %>
                    <%= booking.service.user.fullname %>
                <% end %>
              </span>
            </div>
            <div class="col-md-3 text-right">
                    <%= render partial: "reviews/traveler_form", locals: {reservation: booking} %>
            </div>


          </div>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reservations/your_reservations.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", services_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your bookings", your_bookings_path, class: "sidebar-link active" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Your Reservations
      </div>
      <div class="panel-body">

        <% @services.each do |service| %>
            <% service.reservations.each do |reservation| %>
                <div class="row">
                  <div class="col-md-2">
                    <%= reservation.start_date.strftime('%v') %>
                  </div>
                  <div class="col-md-2">
                    <%= link_to service_path(reservation.service) do %>
                        <%= image_tag reservation.service.cover_photo(:thumb) %>
                    <% end %>
                  </div>
                  <div class="col-md-5">
                    <%= link_to reservation.service.guide_name, service_path(reservation.service) %><br/><br/>
                    <span>
                      <%= link_to user_path(reservation.user) do %>
                        <%= image_tag avatar_url(reservation.user), class: "img-circle avatar-small" %> <br/>
                        <%= reservation.user.fullname %>
                      <% end %>
                    </span>
                  </div>
                  <div class="col-md-3 text-right">
                    <%= render partial: "reviews/guide_form", locals: {reservation: reservation} %>
                  </div>

                </div>
                <hr/>

            <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>