config/routes.rb
Rails.application.routes.draw do


  root'pages#home'
  devise_for :users,
             controllers: { registrations: 'registrations'}

  resources :users, only: [:show]
  resources :services,except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'expertise_area'
      get 'location'
      get 'preload'
      get 'preview'
    end

    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :traveler_reviews, only: [:create, :detroy]
  resources :guide_reviews, only: [:create, :detroy]

  get '/your_bookings' => 'reservations#your_bookings'
  get '/your_reservations' => 'reservations#your_reservations'
  get 'search' => 'pages#search'

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :service

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def create
    @service = Service.find(params[:service_id])

    if params[:images]
      params[:images].each do |img|
        @service.photos.create(image: img)
      end

      @photos = @service.photos
      redirect_back(fallback_location: request.referer, notice: "Saved...")
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @service = @photo.service

    @photo.destroy
    @photos = Photo.where(service_id: @service.id)

    respond_to :js
  end
end

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
  <br/><br/>

  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag photo.image.url() %>
          </div>
          <div class="panel-body">
            <span class="pull-right">
              <%= link_to service_photo_path(photo.service_id, photo), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/destroy.js.erb
service$('#photos').html("<%= j render 'photo_list' %>")

<% if @service.photos.blank? %>
  $('#photo_check').hide();
<% end %>


<% if !@service.active && !@service.price.blank? && !@service.guide_name.blank? && !@service.photos.blank? && !@service.city.blank? %>
  $('#publish_button').attr('disabled', false);

<% else %>
  $('#publish_button').attr('disabled', true);

<% end %>